### ISSUE TITLE
fetch seems not defined

### ISSUE THREAD

**Issue by JCluzet** [ding-live/ding-node#2]
Hi 👋

I try to run Ding SDK but i got this error when i run authenticate method: 
```
ReferenceError: fetch is not defined
[missmyex-back] [2023-09-30 21:14:31]     at authenticate (/workspace/back/node_modules/@ding-live/sdk/dist/index.js:94:20)
[missmyex-back] [2023-09-30 21:14:31]     at Client.authenticate (/workspace/back/node_modules/@ding-live/sdk/dist/index.js:325:12)
[missmyex-back] [2023-09-30 21:14:31]     at module.exports.authenticate (/workspace/back/dingService.js:11:23)
```

**Comment by JCluzet** [comment]
I've managed to resolve the `ReferenceError: fetch is not defined` issue encountered when calling the authenticate method in the SDK, and wanted to share the solution here for the benefit of others who might face a similar problem.

Problem:
When attempting to utilize the authenticate method from the SDK in a Node.js environment, the following error was observed:
```

ReferenceError: fetch is not defined
[2023-09-30 21:14:31]     at authenticate (/workspace/back/node_modules/@ding-live/sdk/dist/index.js:94:20)
[2023-09-30 21:14:31]     at Client.authenticate (/workspace/back/node_modules/@ding-live/sdk/dist/index.js:325:12)
[2023-09-30 21:14:31]     at module.exports.authenticate (/workspace/back/dingService.js:11:23)
```

Solution:
The issue appears to stem from the absence of a fetch implementation in the Node.js environment, which is required by the SDK. To resolve the issue, I added a fetch polyfill using node-fetch and utilized an asynchronous import to assign it globally, as follows:

```
import("node-fetch").then((module) => {
  global.fetch = module.default;
});
```
It would be super helpful if this dependency and resolution could be documented in the SDK documentation to assist developers in troubleshooting similar issues in the future. Alternatively, incorporating a check within the SDK to provide a clearer error message or automatically polyfill fetch in non-browser environments might enhance developer experience.

Thank you for providing this tool and I hope this information assists others in resolving similar challenges! 🚀
